config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "questions#index"

  resources :questions do
    get :delete_attachment, on: :member
    resources :answers, shallow: true do
      get :update_to_best_answer, on: :member
      get :delete_attachment, on: :member
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_many_attached :files

  validates :body, presence: :true

  def mark_as_best
    transaction do
      self.question.answers.update_all(best_answer: false)
      self.update(best_answer: true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  has_many_attached :files
  
  validates :title, :body, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  def author_of?(resourse)
    self.id == resourse.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: :create
  before_action :set_answer, only: [:update, :destroy, :update_to_best_answer, :delete_attachment]
  before_action :get_list_of_answers, only: [:update, :update_to_best_answer, :delete_attachment]

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  def update_to_best_answer
    @answer.mark_as_best if current_user.author_of?(@answer.question)
  end

  def delete_attachment
    if current_user.author_of?(@answer)
      @answer.files.where(id: params[:file_id]).purge
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [])
  end

  def get_list_of_answers
    set_answer
    @answers = Answer.where(question_id: @answer.question_id).order(best_answer: :desc, created_at: :asc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy, :delete_attachment]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answers = @question.answers.order(best_answer: :desc, created_at: :asc)
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted'
    else
      flash[:alert] = "You can't delete another user's question"
    end
  end

  def delete_attachment
    if current_user.author_of?(@question)
      @question.files.where(id: params[:file_id]).purge
      redirect_to @question
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
.answer id="answer-#{answer.id}"
  p= answer.body
  -if answer.files.attached?
    - answer.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      -if current_user&.author_of?(answer)
        p= link_to 'Delete file', delete_attachment_answer_path(answer, file_id: file.id), remote: true

  - if user_signed_in? && current_user&.author_of?(answer.question)
    p= link_to 'Best answer', update_to_best_answer_answer_path(answer, question_id: answer.question_id), remote: true, id: "best-answer-#{answer.id}"

  - if user_signed_in? && answer.persisted? && current_user&.author_of?(answer)
    p= link_to "Edit", '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    p= link_to 'Delete', answer_path(answer), method: :delete, remote: true

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false, direct_upload: true  do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true
      = f.submit 'Save'

app/views/answers/create.js.erb
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer-errors').empty();
<% else %>
  $('.new-answer-errors').html('<%= j render "shared/errors", resource: @answer %>');
<% end %>

app/views/answers/delete_attachment.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/answers/destroy.js.erb
$("div#answer-<%= @answer.id %>").remove();

app/views/answers/update.js.erb
<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @answers %>');
<% else %>
  $('form#edit-answer-' + <%= @answer.id %>).append('<%= j render "shared/errors", resource: @answer %>');
<% end %>

app/views/answers/update_to_best_answer.js.erb
$('.answers').html('<%= j render @answers %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QNA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <% if user_signed_in? %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'SignIn', new_user_session_path %> |
      <%= link_to 'SignUp', new_user_registration_path %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true, direct_upload: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p= f.submit 'Save'

app/views/questions/index.html.slim
h1= 'All questions'
ul
  -@questions.each do |question|
    li= link_to "#{question.title}", question_path(question)

p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true, direct_upload: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p= f.submit 'Ask'

app/views/questions/show.html.slim
.question
  h1= @question.title
  p= @question.body

  -if @question.files.attached?
    - @question.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      -if current_user&.author_of?(@question)
        p= link_to 'Delete', delete_attachment_question_path(@question, file_id: file.id)

  -if current_user&.author_of?(@question) && user_signed_in?
    p= link_to 'Edit question', edit_question_path(@question)
    p= link_to 'Delete question', question_path(@question), method: :delete

.answers
  p List of answers
  = render @answers

= form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.label :files
  = f.file_field :files, multiple: true
  = f.submit 'Reply'

.new-answer-errors

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message